-- File generated by the BNF Converter (bnfc 2.9.4).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for PrintCringe.

module PrintCringe where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified AbsCringe

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print AbsCringe.Ident where
  prt _ (AbsCringe.Ident i) = doc $ showString i
instance Print (AbsCringe.Program' a) where
  prt i = \case
    AbsCringe.Program _ stmts -> prPrec i 0 (concatD [prt 0 stmts])

instance Print (AbsCringe.Block' a) where
  prt i = \case
    AbsCringe.Block _ stmts -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stmts, doc (showString "}")])

instance Print [AbsCringe.Stmt' a] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (AbsCringe.Stmt' a) where
  prt i = \case
    AbsCringe.Empty _ -> prPrec i 0 (concatD [doc (showString ";")])
    AbsCringe.BStmt _ block -> prPrec i 0 (concatD [prt 0 block])
    AbsCringe.Decl _ type_ item -> prPrec i 0 (concatD [prt 0 type_, prt 0 item, doc (showString ";")])
    AbsCringe.ConstDecl _ type_ item -> prPrec i 0 (concatD [doc (showString "immutable"), prt 0 type_, prt 0 item, doc (showString ";")])
    AbsCringe.Ass _ id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr, doc (showString ";")])
    AbsCringe.Incr _ id_ -> prPrec i 0 (concatD [doc (showString "inc"), prt 0 id_, doc (showString ";")])
    AbsCringe.Decr _ id_ -> prPrec i 0 (concatD [doc (showString "dec"), prt 0 id_, doc (showString ";")])
    AbsCringe.Ret _ expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr, doc (showString ";")])
    AbsCringe.VRet _ -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    AbsCringe.Cond _ expr stmt -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    AbsCringe.CondElse _ expr block1 block2 -> prPrec i 0 (concatD [doc (showString "if"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 block1, doc (showString "else"), prt 0 block2])
    AbsCringe.While _ expr stmt -> prPrec i 0 (concatD [doc (showString "while"), doc (showString "("), prt 0 expr, doc (showString ")"), prt 0 stmt])
    AbsCringe.For _ id_ expr1 expr2 stmt -> prPrec i 0 (concatD [doc (showString "from"), prt 0 id_, doc (showString "="), prt 0 expr1, doc (showString "to"), prt 0 expr2, doc (showString "do"), prt 0 stmt])
    AbsCringe.Print _ expr -> prPrec i 0 (concatD [doc (showString "print"), prt 0 expr, doc (showString ";")])
    AbsCringe.Break _ -> prPrec i 0 (concatD [doc (showString "exit"), doc (showString ";")])
    AbsCringe.Continue _ -> prPrec i 0 (concatD [doc (showString "skip"), doc (showString ";")])
    AbsCringe.SExp _ expr -> prPrec i 0 (concatD [prt 0 expr, doc (showString ";")])

instance Print (AbsCringe.Item' a) where
  prt i = \case
    AbsCringe.NoInit _ id_ -> prPrec i 0 (concatD [prt 0 id_])
    AbsCringe.Init _ id_ expr -> prPrec i 0 (concatD [prt 0 id_, doc (showString "="), prt 0 expr])

instance Print (AbsCringe.Type' a) where
  prt i = \case
    AbsCringe.Int _ -> prPrec i 0 (concatD [doc (showString "int")])
    AbsCringe.Char _ -> prPrec i 0 (concatD [doc (showString "char")])
    AbsCringe.Str _ -> prPrec i 0 (concatD [doc (showString "string")])
    AbsCringe.Bool _ -> prPrec i 0 (concatD [doc (showString "bool")])
    AbsCringe.Fun _ argtypes rettype -> prPrec i 0 (concatD [doc (showString "fun"), doc (showString "["), prt 0 argtypes, doc (showString "->"), prt 0 rettype, doc (showString "]")])

instance Print (AbsCringe.ArgType' a) where
  prt i = \case
    AbsCringe.Val _ type_ -> prPrec i 0 (concatD [prt 0 type_])
    AbsCringe.Ref _ type_ -> prPrec i 0 (concatD [doc (showString "ref"), prt 0 type_])

instance Print [AbsCringe.ArgType' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (AbsCringe.RetType' a) where
  prt i = \case
    AbsCringe.NoVoid _ type_ -> prPrec i 0 (concatD [prt 0 type_])
    AbsCringe.Void _ -> prPrec i 0 (concatD [])

instance Print (AbsCringe.Arg' a) where
  prt i = \case
    AbsCringe.Arg _ argtype id_ -> prPrec i 0 (concatD [prt 0 argtype, prt 0 id_])

instance Print [AbsCringe.Arg' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (AbsCringe.Expr' a) where
  prt i = \case
    AbsCringe.EVar _ id_ -> prPrec i 6 (concatD [prt 0 id_])
    AbsCringe.ELitInt _ n -> prPrec i 6 (concatD [prt 0 n])
    AbsCringe.ELitChar _ c -> prPrec i 6 (concatD [prt 0 c])
    AbsCringe.EString _ str -> prPrec i 6 (concatD [printString str])
    AbsCringe.ELitTrue _ -> prPrec i 6 (concatD [doc (showString "true")])
    AbsCringe.ELitFalse _ -> prPrec i 6 (concatD [doc (showString "false")])
    AbsCringe.ELambda _ args rettype block -> prPrec i 6 (concatD [doc (showString "("), prt 0 args, doc (showString ")"), doc (showString "->"), prt 0 rettype, prt 0 block])
    AbsCringe.EApp _ id_ exprs -> prPrec i 6 (concatD [prt 0 id_, doc (showString "("), prt 0 exprs, doc (showString ")")])
    AbsCringe.Neg _ expr -> prPrec i 5 (concatD [doc (showString "-"), prt 6 expr])
    AbsCringe.Not _ expr -> prPrec i 5 (concatD [doc (showString "not"), prt 6 expr])
    AbsCringe.EMul _ expr1 mulop expr2 -> prPrec i 4 (concatD [prt 4 expr1, prt 0 mulop, prt 5 expr2])
    AbsCringe.EAdd _ expr1 addop expr2 -> prPrec i 3 (concatD [prt 3 expr1, prt 0 addop, prt 4 expr2])
    AbsCringe.ERel _ expr1 relop expr2 -> prPrec i 2 (concatD [prt 2 expr1, prt 0 relop, prt 3 expr2])
    AbsCringe.EAnd _ expr1 expr2 -> prPrec i 1 (concatD [prt 2 expr1, doc (showString "and"), prt 1 expr2])
    AbsCringe.EOr _ expr1 expr2 -> prPrec i 0 (concatD [prt 1 expr1, doc (showString "or"), prt 0 expr2])

instance Print [AbsCringe.Expr' a] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print (AbsCringe.AddOp' a) where
  prt i = \case
    AbsCringe.Plus _ -> prPrec i 0 (concatD [doc (showString "+")])
    AbsCringe.Minus _ -> prPrec i 0 (concatD [doc (showString "-")])

instance Print (AbsCringe.MulOp' a) where
  prt i = \case
    AbsCringe.Times _ -> prPrec i 0 (concatD [doc (showString "*")])
    AbsCringe.Div _ -> prPrec i 0 (concatD [doc (showString "/")])
    AbsCringe.Mod _ -> prPrec i 0 (concatD [doc (showString "mod")])

instance Print (AbsCringe.RelOp' a) where
  prt i = \case
    AbsCringe.LTH _ -> prPrec i 0 (concatD [doc (showString "<")])
    AbsCringe.LE _ -> prPrec i 0 (concatD [doc (showString "<=")])
    AbsCringe.GTH _ -> prPrec i 0 (concatD [doc (showString ">")])
    AbsCringe.GE _ -> prPrec i 0 (concatD [doc (showString ">=")])
    AbsCringe.EQU _ -> prPrec i 0 (concatD [doc (showString "is")])
    AbsCringe.NE _ -> prPrec i 0 (concatD [doc (showString "is"), doc (showString "not")])
