## File generated by the BNF Converter (bnfc 2.9.4).

# Makefile for building the parser and test program.

GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : TestCringe

# Rules for building the parser.

AbsCringe.hs LexCringe.x ParCringe.y PrintCringe.hs TestCringe.hs : cringe.cf
	bnfc --haskell --functor cringe.cf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

TestCringe : AbsCringe.hs LexCringe.hs ParCringe.hs PrintCringe.hs TestCringe.hs
	${GHC} ${GHC_OPTS} $@

# Rules for cleaning generated files.

clean :
	-rm -f *.hi *.o *.log *.aux *.dvi

distclean : clean
	-rm -f AbsCringe.hs AbsCringe.hs.bak ComposOp.hs ComposOp.hs.bak DocCringe.txt DocCringe.txt.bak ErrM.hs ErrM.hs.bak LayoutCringe.hs LayoutCringe.hs.bak LexCringe.x LexCringe.x.bak ParCringe.y ParCringe.y.bak PrintCringe.hs PrintCringe.hs.bak SkelCringe.hs SkelCringe.hs.bak TestCringe.hs TestCringe.hs.bak XMLCringe.hs XMLCringe.hs.bak ASTCringe.agda ASTCringe.agda.bak ParserCringe.agda ParserCringe.agda.bak IOLib.agda IOLib.agda.bak Main.agda Main.agda.bak cringe.dtd cringe.dtd.bak TestCringe LexCringe.hs ParCringe.hs ParCringe.info ParDataCringe.hs Makefile


# EOF
